# ~\~ language=YAML filename=tutorials/plutus/docker-compose.yml
# ~\~ begin <<docs/06-Plutus-transactions.md|tutorials/plutus/docker-compose.yml>>[0]
version: '3'

services:
  cardano-node:
    image: inputoutput/cardano-node
    volumes:
      # take uid/gid lists from host
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      # this will break as soon as we change the name of the job sync_and_cache
      - node-ipc:/ipc
      - /home/runner/work/_temp/db-testnet/:/data/db/
    environment:
      - NETWORK=testnet

  node:
    image: inputoutput/cardano-node
    volumes:
      # take uid/gid lists from host
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - node-ipc:/ipc:ro
      - ./:/plutus/
    working_dir: /plutus/
    tty: true
    stdin_open: true
    environment:
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
    command: cli
    profiles:
      - node
    depends_on:
      - cardano-node

  plutus:
    image: inputoutput/plutus-starter-devcontainer

volumes:
  node-ipc:
    external: false
# ~\~ end
