name: experiment-docker-cache

on:
  # schedule:
  #  - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  read_cache:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        network: [testnet]
        cardanoNodeVersion: [1.34.1]

    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v2.3.3

      - name: ⌚ Get Date/Time
        id: date-time
        shell: bash
        run: |
          echo "::set-output name=value::$(/bin/date -u "+%Y%m%d-%H%M%S")" #

      - name: 💾 Cache cardano-node DB
        id: cache
        uses: actions/cache@v2.1.1
        with:
          path: ${{ runner.temp }}/db-${{ matrix.network }}
          key: cardano-node-${{ matrix.network }}-${{ steps.date-time.outputs.value }}
          restore-keys: |
            cardano-node-${{ matrix.network }}-

      - name: run the architecture with docker compose
        run: docker-compose up --renew-anon-volumes --detach
      - name: see if it's running
        run: |
          ls -l /home/runner/work/_temp/db-testnet/
          docker-compose run --entrypoint="/bin/bash" cardano-node -c "ls -l $(pwd); ls -l /data; ls -l /data/db/ "
          sleep 60s
          docker-compose run --entrypoint="/bin/bash" node -c "ls -l $(pwd); ls -al /data "
          sleep 60s
          docker-compose run node cli query tip --testnet-magic 1097911063
          sleep 120
          docker-compose run node cli query tip --testnet-magic 1097911063
          sleep 120
          docker-compose run node cli query tip --testnet-magic 1097911063
      - name: stop
        run: docker-compose down -v
