name: experiment-docker-cache

on:
  #  schedule:
  #    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  read_cache:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        network: [testnet]
        cardanoNodeVersion: [1.34.1]

    runs-on: ubuntu-latest
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v2.3.3

    - name: ⌚ Get Date/Time
      id: date-time
      shell: bash
      run: |
        echo "::set-output name=value::$(/bin/date -u "+%Y%m%d-%H%M%S")" #

    - name: 💾 Cache cardano-node DB
      id: cache
      uses: actions/cache@v2.1.1
      with:
        path: ${{ runner.temp }}/db-${{ matrix.network }}
        key: cardano-node-ogmios-${{ matrix.network }}-${{ steps.date-time.outputs.value }}
        restore-keys: |
          cardano-node-ogmios-${{ matrix.network }}-

    - name: start a cardano-node and a cli docker container
      run: |
        docker pull inputoutput/cardano-node
        docker run --detach --name cardano-node \
          -v ${{ runner.temp }}/db-${{ matrix.network }}:/data \
          -v ${{ runner.temp }}/ipc:/ipc \
          -e NETWORK=testnet

        docker run --detach --name node \
        -v ${{ runner.temp }}/ipc:/ipc:ro \
        -e CARDANO_NODE_SOCKET_PATH=/ipc/node.socket

    # - name: Create a docker volume with the db from cache loaded
    #   #https://stackoverflow.com/a/67280719/54848
    #   run: |
    #     docker volume create myapplicationdata
    #     docker volume inspect myapplicationdata
    #     sudo rm -rf /var/lib/docker/volumes/myapplicationdata/_data/
    #     sudo ln --symbolic --target-directory /var/lib/docker/volumes/myapplicationdata/_data/ ${{ runner.temp }}/db-${{ matrix.network }}
    #     #sudo cp -p -r ${{ runner.temp }}/db-${{ matrix.network }} /var/lib/docker/volumes/myapplicationdata/_data/

    # - name: run the architecture with docker compose
    #   run: docker-compose up --detach
    - name: see if it's running
      run: |
        docker run --entrypoint="/bin/bash" node -c pwd; ls
        docker run node cli query tip --testnet-magic 1097911063
        sleep 120
        docker run node cli query tip --testnet-magic 1097911063
        sleep 120
        docker run node cli query tip --testnet-magic 1097911063
    # - name: stop
    #   run: docker-compose down -v
    - name: stop the containers
      run: |
        docker stop cardano-node
        docker rmi cardano-node
        docker stop node
        docker rmi cardano-node
