name: Network Synchronization

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  sync_and_cache:
    strategy:
      matrix:
        network: [testnet]

    runs-on: ubuntu-latest
    steps:

    - name: 📥 Checkout repository
      uses: actions/checkout@v2.3.3

    - name: ⌚ Get Date/Time
      id: date-time
      shell: bash
      run: |
        echo "::set-output name=value::$(/bin/date -u "+%Y%m%d-%H%M%S")"

    - name: 💾 Cache cardano-node DB
      id: cache
      uses: actions/cache@v2.1.1
      with:
        path: ${{ runner.temp }}/db-${{ matrix.network }}
        key: cardano-node-${{ matrix.network }}-${{ steps.date-time.outputs.value }}
        restore-keys: |
          cardano-node-${{ matrix.network }}-

    - name: ⟲ Sync Node
      uses: CardanoSolutions/gh-action-cardano-node-ogmios-docker-sync@v1.0.1
      with:
        db-dir: ${{ runner.temp }}/db-${{ matrix.network }}
        network: ${{ matrix.network }}
